[2024-06-02T18:00:10.582+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T18:00:10.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T18:00:04.895543+00:00 [queued]>
[2024-06-02T18:00:10.599+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T18:00:04.895543+00:00 [queued]>
[2024-06-02T18:00:10.600+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-02T18:00:10.610+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): transformation_task> on 2024-06-02 18:00:04.895543+00:00
[2024-06-02T18:00:10.617+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=58) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-02T18:00:10.619+0000] {standard_task_runner.py:63} INFO - Started process 60 to run task
[2024-06-02T18:00:10.620+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_redshift', 'transformation_task', 'manual__2024-06-02T18:00:04.895543+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpavp82te6']
[2024-06-02T18:00:10.622+0000] {standard_task_runner.py:91} INFO - Job 347: Subtask transformation_task
[2024-06-02T18:00:10.664+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T18:00:04.895543+00:00 [running]> on host d2f3a545a6fd
[2024-06-02T18:00:10.719+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Team' AIRFLOW_CTX_DAG_ID='api_to_redshift' AIRFLOW_CTX_TASK_ID='transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T18:00:04.895543+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T18:00:04.895543+00:00'
[2024-06-02T18:00:10.720+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T18:00:10.721+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-02T18:00:10.722+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python glue_job.py']
[2024-06-02T18:00:10.732+0000] {subprocess.py:86} INFO - Output:
[2024-06-02T18:00:13.461+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-06-02T18:00:13.462+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/glue_job.py", line 29, in <module>
[2024-06-02T18:00:13.462+0000] {subprocess.py:93} INFO -     response = s3_client.get_object(Bucket=bucket_name, Key=file)
[2024-06-02T18:00:13.463+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.463+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call
[2024-06-02T18:00:13.464+0000] {subprocess.py:93} INFO -     return self._make_api_call(operation_name, kwargs)
[2024-06-02T18:00:13.464+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.465+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/client.py", line 989, in _make_api_call
[2024-06-02T18:00:13.465+0000] {subprocess.py:93} INFO -     http, parsed_response = self._make_request(
[2024-06-02T18:00:13.466+0000] {subprocess.py:93} INFO -                             ^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.466+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/client.py", line 1015, in _make_request
[2024-06-02T18:00:13.467+0000] {subprocess.py:93} INFO -     return self._endpoint.make_request(operation_model, request_dict)
[2024-06-02T18:00:13.467+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.467+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
[2024-06-02T18:00:13.468+0000] {subprocess.py:93} INFO -     return self._send_request(request_dict, operation_model)
[2024-06-02T18:00:13.469+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.469+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 198, in _send_request
[2024-06-02T18:00:13.470+0000] {subprocess.py:93} INFO -     request = self.create_request(request_dict, operation_model)
[2024-06-02T18:00:13.471+0000] {subprocess.py:93} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.471+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 134, in create_request
[2024-06-02T18:00:13.471+0000] {subprocess.py:93} INFO -     self._event_emitter.emit(
[2024-06-02T18:00:13.472+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
[2024-06-02T18:00:13.472+0000] {subprocess.py:93} INFO -     return self._emitter.emit(aliased_event_name, **kwargs)
[2024-06-02T18:00:13.473+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.473+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
[2024-06-02T18:00:13.474+0000] {subprocess.py:93} INFO -     return self._emit(event_name, kwargs)
[2024-06-02T18:00:13.474+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.474+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
[2024-06-02T18:00:13.475+0000] {subprocess.py:93} INFO -     response = handler(**kwargs)
[2024-06-02T18:00:13.475+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.476+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/signers.py", line 105, in handler
[2024-06-02T18:00:13.476+0000] {subprocess.py:93} INFO -     return self.sign(operation_name, request)
[2024-06-02T18:00:13.477+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-02T18:00:13.478+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/signers.py", line 195, in sign
[2024-06-02T18:00:13.478+0000] {subprocess.py:93} INFO -     auth.add_auth(request)
[2024-06-02T18:00:13.479+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
[2024-06-02T18:00:13.480+0000] {subprocess.py:93} INFO -     raise NoCredentialsError()
[2024-06-02T18:00:13.480+0000] {subprocess.py:93} INFO - botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2024-06-02T18:00:13.559+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-02T18:00:13.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T18:00:13.570+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-02T18:00:13.573+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_to_redshift, task_id=transformation_task, run_id=manual__2024-06-02T18:00:04.895543+00:00, execution_date=20240602T180004, start_date=20240602T180010, end_date=20240602T180013
[2024-06-02T18:00:13.582+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 347 for task transformation_task (Bash command failed. The command returned a non-zero exit code 1.; 60)
[2024-06-02T18:00:13.612+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T18:00:13.629+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T18:00:13.632+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
