[2024-06-02T12:25:18.229+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:25:18.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T12:25:14.111258+00:00 [queued]>
[2024-06-02T12:25:18.245+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T12:25:14.111258+00:00 [queued]>
[2024-06-02T12:25:18.245+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-02T12:25:18.252+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): transformation_task> on 2024-06-02 12:25:14.111258+00:00
[2024-06-02T12:25:18.257+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-02T12:25:18.259+0000] {standard_task_runner.py:63} INFO - Started process 164 to run task
[2024-06-02T12:25:18.260+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_redshift', 'transformation_task', 'manual__2024-06-02T12:25:14.111258+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpidwpgu8r']
[2024-06-02T12:25:18.261+0000] {standard_task_runner.py:91} INFO - Job 229: Subtask transformation_task
[2024-06-02T12:25:18.298+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T12:25:14.111258+00:00 [running]> on host 1d861f4bf9ce
[2024-06-02T12:25:18.351+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Team' AIRFLOW_CTX_DAG_ID='api_to_redshift' AIRFLOW_CTX_TASK_ID='transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T12:25:14.111258+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T12:25:14.111258+00:00'
[2024-06-02T12:25:18.352+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:25:18.353+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-02T12:25:18.354+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python opt/***/scripts/glue_job.py']
[2024-06-02T12:25:18.364+0000] {subprocess.py:86} INFO - Output:
[2024-06-02T12:25:18.404+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpn9ybdwar/opt/***/scripts/glue_job.py': [Errno 2] No such file or directory
[2024-06-02T12:25:18.407+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-06-02T12:25:18.408+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:25:18.417+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-06-02T12:25:18.420+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_to_redshift, task_id=transformation_task, run_id=manual__2024-06-02T12:25:14.111258+00:00, execution_date=20240602T122514, start_date=20240602T122518, end_date=20240602T122518
[2024-06-02T12:25:18.428+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 229 for task transformation_task (Bash command failed. The command returned a non-zero exit code 2.; 164)
[2024-06-02T12:25:18.477+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:25:18.493+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:25:18.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
