[2024-06-02T12:29:30.195+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:29:30.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T12:29:25.806704+00:00 [queued]>
[2024-06-02T12:29:30.211+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T12:29:25.806704+00:00 [queued]>
[2024-06-02T12:29:30.211+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-02T12:29:30.218+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): transformation_task> on 2024-06-02 12:29:25.806704+00:00
[2024-06-02T12:29:30.223+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-02T12:29:30.224+0000] {standard_task_runner.py:63} INFO - Started process 229 to run task
[2024-06-02T12:29:30.225+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_redshift', 'transformation_task', 'manual__2024-06-02T12:29:25.806704+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpy7bviso7']
[2024-06-02T12:29:30.226+0000] {standard_task_runner.py:91} INFO - Job 231: Subtask transformation_task
[2024-06-02T12:29:30.264+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_redshift.transformation_task manual__2024-06-02T12:29:25.806704+00:00 [running]> on host 1d861f4bf9ce
[2024-06-02T12:29:30.321+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Team' AIRFLOW_CTX_DAG_ID='api_to_redshift' AIRFLOW_CTX_TASK_ID='transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T12:29:25.806704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T12:29:25.806704+00:00'
[2024-06-02T12:29:30.323+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:29:30.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-02T12:29:30.325+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../opt/***/scripts/glue_job.py']
[2024-06-02T12:29:30.335+0000] {subprocess.py:86} INFO - Output:
[2024-06-02T12:29:30.378+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpzvtnuc1l/../opt/***/scripts/glue_job.py': [Errno 2] No such file or directory
[2024-06-02T12:29:30.381+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-06-02T12:29:30.382+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:29:30.391+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-06-02T12:29:30.394+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_to_redshift, task_id=transformation_task, run_id=manual__2024-06-02T12:29:25.806704+00:00, execution_date=20240602T122925, start_date=20240602T122930, end_date=20240602T122930
[2024-06-02T12:29:30.402+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 231 for task transformation_task (Bash command failed. The command returned a non-zero exit code 2.; 229)
[2024-06-02T12:29:30.440+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:29:30.455+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:29:30.458+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
